### ISSUE TITLE
function and structure

### ISSUE THREAD

**Issue by xorgxx** [jreziga/JRKPaymentSipsBundle#1]
Hi i have to install payment ATOS. i m looking your bundle, but i dont see are it is working !.
can you give graphe procedure are it work with ATOS. for exemple you never speak abort "request bin"

thank

**Comment by jr-k** [comment]
Hi,

Did you followed all the "readme" file ? 

You just have to :
1. Install the bundle via composer
2. Add it to your AppKernel
3. Put the files the bank gave you like that :

```
|-- app
|   `-- config
|       `-- sips
|       `-- bin
|           `-- static
|              `-- request
|              `-- response
|       `-- param
|           `-- certif.XXXXXXXXXXXX
|           `-- parmcom.XXXXXXXXXXXX
|           `-- parmcom.mercanet        # if you are using mercanet for example
|           `-- pathfile                # generated
|       `-- Version.txt
```

4 . Edit the configuration with your credentials

```
jrk_payment_sips:
    files:
        sips_pathfile: "%kernel.root_dir%/config/sips/param/pathfile"
        sips_request: "%kernel.root_dir%/config/sips/bin/static/request"
        sips_response: "%kernel.root_dir%/config/sips/bin/static/response"
        sips_logs: "%kernel.root_dir%/logs/sips.log"
    params:
        sips_merchant_id: "XXXXXXXXXXXXXXXXXX"
        sips_currency_code: "EUR"   # OR use the currency_code provided by ATOS (978=EUR for example)
        sips_language: "fr"
        sips_payment_means: "CB,2,VISA,2,MASTERCARD,2"
        sips_header_flag: "yes"
        sips_merchant_country: "fr"
    links:
        sips_cancel_return_url: "my_homepage_route"     # Route to redirect if the payment is canceled
        sips_route_response: "my_sips_response"         # Route to redirect if the payment is accepted
```

5 . Execute "php app/console jrk:sips:install" which will generate you the app\config\sips\param\pathfile. For example, the pathfile will look like that :

```
DEBUG!YES!
D_LOGO!/bundles/jrkpaymentsips/sips/logo/!
F_DEFAULT!/home/prod/www/projectname/app/config/sips/param/parmcom.sogenactif!
F_PARAM!/home/prod/www/projectname/app/config/sips/param/parmcom!
F_CERTIFICATE!/home/prod/www/projectname/app/config/sips/param/certif!
F_CTYPE!!
```

6 . Add routes import in app/config/routing.yml

```
jrk_payment_sips:
    resource: "@JRKPaymentSipsBundle/Resources/config/routing.yml"
    prefix: /payment
```

Done.

Now in your bundle you can declare 2 routes for example. One for request and one for response. You have an example at the end of readme file.

Hope you'll succeed !
